/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproje;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muhammed
 */
public class AdminSecim extends javax.swing.JFrame {

    DefaultTableModel modelimOdaListe = new DefaultTableModel(); // Baska fonksiyonlardada kullanilacagi için global degişken yapılmıştır.
    DefaultTableModel modelimMusteriListe = new DefaultTableModel();
    public static int seciliOda;
    public static String odaTipi;
    public static int rezervasyonTipi;
    public static int siparisTipi;
    public static int odaNo;

    public void panelDegis(JPanel panel) { // Menu degişimi için panelleri degiştiriyor.
        jLayeredpnlAna.removeAll();
        jLayeredpnlAna.add(panel);
        jLayeredpnlAna.repaint();
        jLayeredpnlAna.revalidate();
    }

    public void menuLabelDegis() { // Menu degişirken menu labellerinin rengini eski hallerine getiriyor.
        jlblMusteriEkle.setForeground(Color.white);
        jlblMusteriEkle.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\müsteriEkle_Beyaz.png"));

        jlblMusteriCikis.setForeground(Color.white);
        jlblMusteriCikis.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\müsteriCikis_Beyaz.png"));

        jlblSistemGünlügü.setForeground(Color.white);
        jlblSistemGünlügü.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\sistemGünlügü_Beyaz.png"));

        jlblSiparis.setForeground(Color.white);
        jlblSiparis.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\siparis_Beyaz.png"));

        jlblOdalar.setForeground(Color.white);
        jlblOdalar.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\odalar_Beyaz.png"));
        
        jlblKullanici.setForeground(Color.white);
        jlblKullanici.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\kullanici_Beyaz.png"));
    }

    /**
     * Creates new form AdminSecim
     */
    public AdminSecim() {
        initComponents();
        System.setProperty("myColor", "#829afb"); // Menu renk degişimi için oluşturulmuş özel renk tonu.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredpnlAna = new javax.swing.JLayeredPane();
        jpnlMusteriEkle = new javax.swing.JPanel();
        jTextFieldKisiSayi = new javax.swing.JTextField();
        jtxtisim = new javax.swing.JTextField();
        jTextFieldSoyisim1 = new javax.swing.JTextField();
        jbtnMusteriEkle = new javax.swing.JButton();
        jButtonAra = new javax.swing.JButton();
        jTextFieldYas = new javax.swing.JTextField();
        jTextFieldMeslek = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOda = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jcmbbxRezervasyonTip = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jpnlMusteriCikis = new javax.swing.JPanel();
        jBtnMusteriCikis = new javax.swing.JButton();
        jTxtOdaNo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jbtnucretHesap = new javax.swing.JButton();
        jlblUcretMiktar = new javax.swing.JLabel();
        jlblUcret = new javax.swing.JLabel();
        jpnlOdalar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableOdaListe = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jCmbbxOdaTip = new javax.swing.JComboBox<>();
        jcmbbxOdaDurum = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jpnlSiparis = new javax.swing.JPanel();
        jtxtSiparisOdaNo = new javax.swing.JTextField();
        jbtnSiparisOnay = new javax.swing.JButton();
        jcmbbtnSiparisTipi = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jpnlSistemGünlügü = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblSistemgunlugu = new javax.swing.JTable();
        jbtnSistemGunlugunuGoster = new javax.swing.JButton();
        jpnlKullanici = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jtxtKullaniciAd = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jtxtKullaniciSoyad = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jtxtKullaniciHesap = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jtxtKullaniciSifre = new javax.swing.JTextField();
        jcmbboxKullaniciYetki = new javax.swing.JComboBox<>();
        jlblKullaniciYetki = new javax.swing.JLabel();
        jbtnKullaniciEkle = new javax.swing.JButton();
        jlblKullaniciEkleHata = new javax.swing.JLabel();
        jlblKullaniciEkle = new javax.swing.JLabel();
        jlblKullaniciEkle1 = new javax.swing.JLabel();
        jtxtKullaniciHesapSil = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jbtnKullaniciSil = new javax.swing.JButton();
        jlblKullaniciSilHata = new javax.swing.JLabel();
        jlblKullaniciGuncelle = new javax.swing.JLabel();
        jtxtKullaniciHesapGuncelle = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jtxtKullaniciSifreGuncelle = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jbtnKullaniciGuncelle = new javax.swing.JButton();
        jlblKullaniciYetkiGuncelle = new javax.swing.JLabel();
        jcmbboxKullaniciYetkiGuncelle = new javax.swing.JComboBox<>();
        jlblKullaniciGuncelleHata = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jlblSiparis = new javax.swing.JLabel();
        jlblSistemGünlügü = new javax.swing.JLabel();
        jlblMusteriEkle = new javax.swing.JLabel();
        jlblMusteriCikis = new javax.swing.JLabel();
        jlblMinimizebtn = new javax.swing.JLabel();
        jlblExitbtn = new javax.swing.JLabel();
        jlblOdalar = new javax.swing.JLabel();
        jlblKullanici = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredpnlAna.setPreferredSize(new java.awt.Dimension(400, 300));
        jLayeredpnlAna.setLayout(new java.awt.CardLayout());

        jpnlMusteriEkle.setBackground(new java.awt.Color(255, 255, 255));
        jpnlMusteriEkle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpnlMusteriEkle.setPreferredSize(new java.awt.Dimension(120, 920));
        jpnlMusteriEkle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldKisiSayi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldKisiSayi.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldKisiSayi.setText("Kişi Sayısı");
        jTextFieldKisiSayi.setBorder(null);
        jTextFieldKisiSayi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldKisiSayiMouseClicked(evt);
            }
        });
        jTextFieldKisiSayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKisiSayiActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jTextFieldKisiSayi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 280, 25));

        jtxtisim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtisim.setForeground(new java.awt.Color(153, 153, 153));
        jtxtisim.setText("Müşteri Adı");
        jtxtisim.setToolTipText("");
        jtxtisim.setBorder(null);
        jtxtisim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtisimMouseClicked(evt);
            }
        });
        jtxtisim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtisimActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jtxtisim, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 280, 25));

        jTextFieldSoyisim1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSoyisim1.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldSoyisim1.setText("Müşteri Soyadı");
        jTextFieldSoyisim1.setBorder(null);
        jTextFieldSoyisim1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSoyisim1MouseClicked(evt);
            }
        });
        jTextFieldSoyisim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoyisim1ActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jTextFieldSoyisim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 280, 25));

        jbtnMusteriEkle.setText("Müşteriyi Ekle");
        jbtnMusteriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMusteriEkleActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jbtnMusteriEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        jButtonAra.setText("Ara");
        jButtonAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAraActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jButtonAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jTextFieldYas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldYas.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldYas.setText("Müşteri Yaşı");
        jTextFieldYas.setBorder(null);
        jTextFieldYas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldYasMouseClicked(evt);
            }
        });
        jTextFieldYas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYasActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jTextFieldYas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 280, 25));

        jTextFieldMeslek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldMeslek.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldMeslek.setText("Müşteri Mesleği");
        jTextFieldMeslek.setBorder(null);
        jTextFieldMeslek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMeslekMouseClicked(evt);
            }
        });
        jTextFieldMeslek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeslekActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jTextFieldMeslek, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 280, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Oda Tipi");
        jpnlMusteriEkle.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tarih");
        jpnlMusteriEkle.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomik", "Normal", "Kral" }));
        jpnlMusteriEkle.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 102, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        jTableOda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jTableOda.setGridColor(new java.awt.Color(255, 255, 255));
        jTableOda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOdaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableOda);

        jpnlMusteriEkle.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 440, 78));
        jpnlMusteriEkle.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 280, 10));
        jpnlMusteriEkle.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 280, 10));
        jpnlMusteriEkle.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 280, 10));
        jpnlMusteriEkle.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 280, 10));
        jpnlMusteriEkle.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 280, 10));

        jcmbbxRezervasyonTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sadece Oda", "Yarım Pansiyon", "Tam Pansiyon", "Her şey Dahil" }));
        jcmbbxRezervasyonTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbbxRezervasyonTipActionPerformed(evt);
            }
        });
        jpnlMusteriEkle.add(jcmbbxRezervasyonTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 102, 25));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Rezervasyon Tipi");
        jpnlMusteriEkle.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 147, -1));
        jpnlMusteriEkle.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 280, 10));
        jpnlMusteriEkle.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 30, 100, -1));

        jLayeredpnlAna.add(jpnlMusteriEkle, "card8");

        jpnlMusteriCikis.setBackground(new java.awt.Color(255, 255, 255));

        jBtnMusteriCikis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnMusteriCikis.setText("Çıkışı Yap");
        jBtnMusteriCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMusteriCikisActionPerformed(evt);
            }
        });

        jTxtOdaNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtOdaNo.setForeground(new java.awt.Color(153, 153, 153));
        jTxtOdaNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtOdaNo.setText("Oda No");
        jTxtOdaNo.setBorder(null);
        jTxtOdaNo.setOpaque(false);
        jTxtOdaNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtOdaNoMouseClicked(evt);
            }
        });
        jTxtOdaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtOdaNoActionPerformed(evt);
            }
        });

        jbtnucretHesap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbtnucretHesap.setText("Ücreti Hesapla");
        jbtnucretHesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnucretHesapActionPerformed(evt);
            }
        });

        jlblUcretMiktar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jlblUcret.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblUcret.setText("Ücret :");

        javax.swing.GroupLayout jpnlMusteriCikisLayout = new javax.swing.GroupLayout(jpnlMusteriCikis);
        jpnlMusteriCikis.setLayout(jpnlMusteriCikisLayout);
        jpnlMusteriCikisLayout.setHorizontalGroup(
            jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMusteriCikisLayout.createSequentialGroup()
                .addGroup(jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnMusteriCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnlMusteriCikisLayout.createSequentialGroup()
                            .addGap(349, 349, 349)
                            .addGroup(jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator6)
                                .addComponent(jTxtOdaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpnlMusteriCikisLayout.createSequentialGroup()
                            .addGap(323, 323, 323)
                            .addGroup(jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpnlMusteriCikisLayout.createSequentialGroup()
                                    .addComponent(jlblUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlblUcretMiktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jbtnucretHesap)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlMusteriCikisLayout.setVerticalGroup(
            jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMusteriCikisLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jTxtOdaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnucretHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnlMusteriCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUcretMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jBtnMusteriCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredpnlAna.add(jpnlMusteriCikis, "card2");

        jpnlOdalar.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        jtableOdaListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jtableOdaListe.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jtableOdaListe);

        jButton2.setText("Odaları Göster");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCmbbxOdaTip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ekonomik", "Normal", "Kral" }));

        jcmbbxOdaDurum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolu", "Boş" }));

        jButton3.setText("Müşterileri Göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlOdalarLayout = new javax.swing.GroupLayout(jpnlOdalar);
        jpnlOdalar.setLayout(jpnlOdalarLayout);
        jpnlOdalarLayout.setHorizontalGroup(
            jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOdalarLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlOdalarLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlOdalarLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcmbbxOdaDurum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCmbbxOdaTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpnlOdalarLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jpnlOdalarLayout.setVerticalGroup(
            jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlOdalarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jCmbbxOdaTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcmbbxOdaDurum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnlOdalarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        jLayeredpnlAna.add(jpnlOdalar, "card5");

        jpnlSiparis.setBackground(new java.awt.Color(255, 255, 255));

        jtxtSiparisOdaNo.setForeground(new java.awt.Color(153, 153, 153));
        jtxtSiparisOdaNo.setText("Oda No");
        jtxtSiparisOdaNo.setBorder(null);
        jtxtSiparisOdaNo.setOpaque(false);
        jtxtSiparisOdaNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSiparisOdaNoMouseClicked(evt);
            }
        });

        jbtnSiparisOnay.setText("Onayla");
        jbtnSiparisOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSiparisOnayActionPerformed(evt);
            }
        });

        jcmbbtnSiparisTipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yemek", "İçecek" }));

        javax.swing.GroupLayout jpnlSiparisLayout = new javax.swing.GroupLayout(jpnlSiparis);
        jpnlSiparis.setLayout(jpnlSiparisLayout);
        jpnlSiparisLayout.setHorizontalGroup(
            jpnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSiparisLayout.createSequentialGroup()
                .addGroup(jpnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlSiparisLayout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jbtnSiparisOnay))
                    .addGroup(jpnlSiparisLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addGroup(jpnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7)
                            .addComponent(jtxtSiparisOdaNo, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jcmbbtnSiparisTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlSiparisLayout.setVerticalGroup(
            jpnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSiparisLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jpnlSiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSiparisOdaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbbtnSiparisTipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jbtnSiparisOnay)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        jLayeredpnlAna.add(jpnlSiparis, "card6");

        jpnlSistemGünlügü.setBackground(new java.awt.Color(255, 255, 255));
        jpnlSistemGünlügü.setPreferredSize(new java.awt.Dimension(847, 564));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setOpaque(false);

        jtblSistemgunlugu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ));
        jtblSistemgunlugu.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(jtblSistemgunlugu);

        jbtnSistemGunlugunuGoster.setText("Sistem Günlüğünü Göster");
        jbtnSistemGunlugunuGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSistemGunlugunuGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlSistemGünlügüLayout = new javax.swing.GroupLayout(jpnlSistemGünlügü);
        jpnlSistemGünlügü.setLayout(jpnlSistemGünlügüLayout);
        jpnlSistemGünlügüLayout.setHorizontalGroup(
            jpnlSistemGünlügüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSistemGünlügüLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addGroup(jpnlSistemGünlügüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlSistemGünlügüLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jbtnSistemGunlugunuGoster)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlSistemGünlügüLayout.setVerticalGroup(
            jpnlSistemGünlügüLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlSistemGünlügüLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbtnSistemGunlugunuGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredpnlAna.add(jpnlSistemGünlügü, "card6");

        jpnlKullanici.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtxtKullaniciAd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciAd.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciAd.setText("Kullanıcı Adı");
        jtxtKullaniciAd.setBorder(null);
        jtxtKullaniciAd.setOpaque(false);
        jtxtKullaniciAd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciAdMouseClicked(evt);
            }
        });
        jtxtKullaniciAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKullaniciAdActionPerformed(evt);
            }
        });

        jtxtKullaniciSoyad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciSoyad.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciSoyad.setText("Kullanıcı Soyadı");
        jtxtKullaniciSoyad.setBorder(null);
        jtxtKullaniciSoyad.setOpaque(false);
        jtxtKullaniciSoyad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciSoyadMouseClicked(evt);
            }
        });

        jtxtKullaniciHesap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciHesap.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciHesap.setText("Hesap Adı");
        jtxtKullaniciHesap.setBorder(null);
        jtxtKullaniciHesap.setOpaque(false);
        jtxtKullaniciHesap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciHesapMouseClicked(evt);
            }
        });

        jtxtKullaniciSifre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciSifre.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciSifre.setText("Şifre");
        jtxtKullaniciSifre.setBorder(null);
        jtxtKullaniciSifre.setOpaque(false);
        jtxtKullaniciSifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciSifreMouseClicked(evt);
            }
        });

        jcmbboxKullaniciYetki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yönetici", "Çalışan" }));

        jlblKullaniciYetki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblKullaniciYetki.setText("Kullanıcı Yetkisi");

        jbtnKullaniciEkle.setText("Ekle");
        jbtnKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKullaniciEkleActionPerformed(evt);
            }
        });

        jlblKullaniciEkleHata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblKullaniciEkleHata.setForeground(new java.awt.Color(255, 0, 51));
        jlblKullaniciEkleHata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciEkleHata.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jlblKullaniciEkle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblKullaniciEkle.setForeground(new java.awt.Color(0, 51, 255));
        jlblKullaniciEkle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciEkle.setText("Kullanıcı Ekle");

        jlblKullaniciEkle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblKullaniciEkle1.setForeground(new java.awt.Color(0, 51, 255));
        jlblKullaniciEkle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciEkle1.setText("Kullanıcı Sil");

        jtxtKullaniciHesapSil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciHesapSil.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciHesapSil.setText("Hesap Adı");
        jtxtKullaniciHesapSil.setBorder(null);
        jtxtKullaniciHesapSil.setOpaque(false);
        jtxtKullaniciHesapSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciHesapSilMouseClicked(evt);
            }
        });

        jbtnKullaniciSil.setText("Sil");
        jbtnKullaniciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKullaniciSilActionPerformed(evt);
            }
        });

        jlblKullaniciSilHata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblKullaniciSilHata.setForeground(new java.awt.Color(255, 0, 51));
        jlblKullaniciSilHata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciSilHata.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jlblKullaniciGuncelle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblKullaniciGuncelle.setForeground(new java.awt.Color(0, 51, 255));
        jlblKullaniciGuncelle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciGuncelle.setText("Kullanıcı Güncelle");

        jtxtKullaniciHesapGuncelle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciHesapGuncelle.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciHesapGuncelle.setText("Hesap Adı");
        jtxtKullaniciHesapGuncelle.setBorder(null);
        jtxtKullaniciHesapGuncelle.setOpaque(false);
        jtxtKullaniciHesapGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciHesapGuncelleMouseClicked(evt);
            }
        });

        jtxtKullaniciSifreGuncelle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtKullaniciSifreGuncelle.setForeground(new java.awt.Color(153, 153, 153));
        jtxtKullaniciSifreGuncelle.setText("Yeni Şifre");
        jtxtKullaniciSifreGuncelle.setBorder(null);
        jtxtKullaniciSifreGuncelle.setOpaque(false);
        jtxtKullaniciSifreGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKullaniciSifreGuncelleMouseClicked(evt);
            }
        });

        jbtnKullaniciGuncelle.setText("Güncelle");
        jbtnKullaniciGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKullaniciGuncelleActionPerformed(evt);
            }
        });

        jlblKullaniciYetkiGuncelle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblKullaniciYetkiGuncelle.setText("Kullanıcı Yetkisi");

        jcmbboxKullaniciYetkiGuncelle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yönetici", "Çalışan" }));

        jlblKullaniciGuncelleHata.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblKullaniciGuncelleHata.setForeground(new java.awt.Color(255, 0, 51));
        jlblKullaniciGuncelleHata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullaniciGuncelleHata.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jpnlKullaniciLayout = new javax.swing.GroupLayout(jpnlKullanici);
        jpnlKullanici.setLayout(jpnlKullaniciLayout);
        jpnlKullaniciLayout.setHorizontalGroup(
            jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jtxtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtKullaniciHesap, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                        .addComponent(jlblKullaniciYetki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcmbboxKullaniciYetki, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jbtnKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblKullaniciEkleHata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jlblKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jlblKullaniciEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtxtKullaniciHesapSil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jbtnKullaniciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlblKullaniciSilHata, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jlblKullaniciGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtxtKullaniciSifreGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlblKullaniciYetkiGuncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbboxKullaniciYetkiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jbtnKullaniciGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblKullaniciGuncelleHata, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jtxtKullaniciHesapGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlKullaniciLayout.setVerticalGroup(
            jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator9)
            .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlKullaniciLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblKullaniciEkle)
                .addGap(40, 40, 40)
                .addComponent(jlblKullaniciEkleHata, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtKullaniciAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtKullaniciSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtKullaniciHesap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtKullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbboxKullaniciYetki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblKullaniciYetki))
                .addGap(30, 30, 30)
                .addComponent(jbtnKullaniciEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jlblKullaniciEkle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblKullaniciSilHata, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jtxtKullaniciHesapSil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jbtnKullaniciSil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlKullaniciLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlblKullaniciGuncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblKullaniciGuncelleHata, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jtxtKullaniciHesapGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtKullaniciSifreGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnlKullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcmbboxKullaniciYetkiGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblKullaniciYetkiGuncelle))))
                .addGap(34, 34, 34)
                .addComponent(jbtnKullaniciGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredpnlAna.add(jpnlKullanici, "card7");

        getContentPane().add(jLayeredpnlAna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 920, 480));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 51, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblSiparis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblSiparis.setForeground(new java.awt.Color(255, 255, 255));
        jlblSiparis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSiparis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/siparis_Beyaz.png"))); // NOI18N
        jlblSiparis.setText("Sipariş");
        jlblSiparis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSiparisMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblSiparis, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 111, 108));

        jlblSistemGünlügü.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblSistemGünlügü.setForeground(new java.awt.Color(255, 255, 255));
        jlblSistemGünlügü.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSistemGünlügü.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sistemGünlügü_Beyaz.png"))); // NOI18N
        jlblSistemGünlügü.setText("Sistem Günlüğü");
        jlblSistemGünlügü.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblSistemGünlügüMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblSistemGünlügü, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 140, 108));

        jlblMusteriEkle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblMusteriEkle.setForeground(new java.awt.Color(130, 154, 251));
        jlblMusteriEkle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMusteriEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/müsteriEkle_Mavi.png"))); // NOI18N
        jlblMusteriEkle.setText("Müşteri Ekle");
        jlblMusteriEkle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMusteriEkleMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblMusteriEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 111, 108));

        jlblMusteriCikis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblMusteriCikis.setForeground(new java.awt.Color(255, 255, 255));
        jlblMusteriCikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMusteriCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/müsteriCikis_Beyaz.png"))); // NOI18N
        jlblMusteriCikis.setText("Müşteri Çıkış");
        jlblMusteriCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMusteriCikisMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblMusteriCikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 111, 108));

        jlblMinimizebtn.setBackground(new java.awt.Color(0, 204, 255));
        jlblMinimizebtn.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlblMinimizebtn.setForeground(new java.awt.Color(255, 255, 255));
        jlblMinimizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMinimizebtn.setText(" - ");
        jlblMinimizebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblMinimizebtn.setPreferredSize(new java.awt.Dimension(27, 32));
        jlblMinimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseExited(evt);
            }
        });
        kGradientPanel1.add(jlblMinimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 30, -1));

        jlblExitbtn.setBackground(new java.awt.Color(214, 45, 32));
        jlblExitbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlblExitbtn.setForeground(new java.awt.Color(255, 255, 255));
        jlblExitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblExitbtn.setText(" X ");
        jlblExitbtn.setMinimumSize(new java.awt.Dimension(27, 32));
        jlblExitbtn.setPreferredSize(new java.awt.Dimension(27, 32));
        jlblExitbtn.setVerifyInputWhenFocusTarget(false);
        jlblExitbtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblExitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseExited(evt);
            }
        });
        kGradientPanel1.add(jlblExitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, -1));

        jlblOdalar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblOdalar.setForeground(new java.awt.Color(255, 255, 255));
        jlblOdalar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblOdalar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/odalar_Beyaz.png"))); // NOI18N
        jlblOdalar.setText("Odalar");
        jlblOdalar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblOdalarMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblOdalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 111, 108));

        jlblKullanici.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblKullanici.setForeground(new java.awt.Color(255, 255, 255));
        jlblKullanici.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblKullanici.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kullanici_Beyaz.png"))); // NOI18N
        jlblKullanici.setText("Kullanıcı");
        jlblKullanici.setToolTipText("");
        jlblKullanici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblKullaniciMouseClicked(evt);
            }
        });
        kGradientPanel1.add(jlblKullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 120, 110));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1293, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSiparisOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSiparisOnayActionPerformed
        // **MÜŞTERİ SİPARİS KISMI

        seciliOda = Integer.parseInt(jtxtSiparisOdaNo.getText());
        siparisTipi = jcmbbtnSiparisTipi.getSelectedIndex();
        Rezervasyon.siparis();
    }//GEN-LAST:event_jbtnSiparisOnayActionPerformed

    private void jlblExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlblExitbtnMouseClicked

    private void jlblExitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseEntered
        System.setProperty("myColor", "#E81123");
        Color myColor = Color.getColor("myColor");
        jlblExitbtn.setBackground(myColor);
        jlblExitbtn.setOpaque(true);

    }//GEN-LAST:event_jlblExitbtnMouseEntered

    private void jlblExitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseExited
        jlblExitbtn.setBackground(Color.white);
        jlblExitbtn.setOpaque(false);

    }//GEN-LAST:event_jlblExitbtnMouseExited

    private void jlblMinimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jlblMinimizebtnMouseClicked

    private void jlblMinimizebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseEntered
        //jlblMinimizebtn.setForeground(Color.GRAY);
        System.setProperty("myColor2", "#829afb");
        Color myColor2 = Color.getColor("myColor2");
        jlblMinimizebtn.setBackground(myColor2);
        jlblMinimizebtn.setOpaque(true);
    }//GEN-LAST:event_jlblMinimizebtnMouseEntered

    private void jlblMinimizebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseExited
        //jlblMinimizebtn.setForeground(Color.BLACK);
        jlblMinimizebtn.setBackground(Color.white);
        jlblMinimizebtn.setOpaque(false);
    }//GEN-LAST:event_jlblMinimizebtnMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // **MÜŞTERİ LİSTELEME

        ResultSet rsMusteri = Otel.display();

        modelimMusteriListe.setRowCount(0); // Her yeni arama yapıldıgında tablonun sıfırlanması için modelimin sutun sayısı 0 yapılmıştır.
        jtableOdaListe.setModel(modelimMusteriListe); // Tabloyu temizliyor.
        Object[] kolonlar = {"Oda No", "Müşteri Adı", "Müşteri Soyadı"}; // Tablonun kolonları
        Object[] satirlar = new Object[3];   // Tablonun sutunları
        modelimMusteriListe.setColumnIdentifiers(kolonlar);
        try {
            if (!rsMusteri.next()) {
                JOptionPane.showMessageDialog(rootPane, "Müşteri Yok...");

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminSecim.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rsMusteri.beforeFirst();
            while (rsMusteri.next()) {
                satirlar[0] = rsMusteri.getString("oda_id");
                satirlar[1] = rsMusteri.getString("musteri_ad");
                satirlar[2] = rsMusteri.getString("musteri_soyad");

                modelimMusteriListe.addRow(satirlar);
                jtableOdaListe.setModel(modelimMusteriListe);

            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminSecim.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // **ODALARI LİSTELEME

        int odaDoluMu;
        if (jcmbbxOdaDurum.getSelectedItem() == "Dolu") {
            odaDoluMu = 1;
        } else {
            odaDoluMu = 0;
        }

        String odaTipi = (String) jCmbbxOdaTip.getSelectedItem();
        String odaDurum = String.valueOf(odaDoluMu);
        Object[] kolonlar = {"Oda No", "Oda Tipi", "Oda Durumu"};
        Object[] sutunlar = new Object[3];

        modelimMusteriListe.setRowCount(0); // Her yeni arama yapıldıgında tablonun sıfırlanması için modelimin sutun sayısı 0 yapılmıştır.
        jTableOda.setModel(modelimMusteriListe); // Tabloyu temizliyor.
        modelimMusteriListe.setColumnIdentifiers(kolonlar);

        ResultSet rsOdalar = Otel.odaListele(odaTipi, odaDurum);

        try {
            while (rsOdalar.next()) {
                sutunlar[0] = rsOdalar.getString("oda_id");
                sutunlar[1] = rsOdalar.getString("oda_tipi");
                sutunlar[2] = rsOdalar.getString("oda_doluMu");

                modelimMusteriListe.addRow(sutunlar);
                jtableOdaListe.setModel(modelimMusteriListe);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminSecim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTxtOdaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtOdaNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtOdaNoActionPerformed

    private void jBtnMusteriCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMusteriCikisActionPerformed
        // **MÜŞTERİ ÇIKIŞ KISMI

        odaNo = Integer.parseInt(jTxtOdaNo.getText());
        if (Rezervasyon.exit()) {
            JOptionPane.showMessageDialog(rootPane, "İşlem Başarıyla Gerçekleştirildi.");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Müşteri Bulunamadı!!!", "HATA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnMusteriCikisActionPerformed

    private void jcmbbxRezervasyonTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbbxRezervasyonTipActionPerformed

    }//GEN-LAST:event_jcmbbxRezervasyonTipActionPerformed

    private void jTableOdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOdaMouseClicked
        jTableOda.getSelectedRow();
    }//GEN-LAST:event_jTableOdaMouseClicked

    private void jTextFieldMeslekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeslekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeslekActionPerformed

    private void jTextFieldMeslekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMeslekMouseClicked
        jTextFieldMeslek.setText("");
        jTextFieldMeslek.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldMeslekMouseClicked

    private void jTextFieldYasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYasActionPerformed

    private void jTextFieldYasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldYasMouseClicked
        jTextFieldYas.setText("");
        jTextFieldYas.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldYasMouseClicked

    private void jButtonAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAraActionPerformed
        // **ODA ARAMA KISMI

        DateFormat tarihFormati = new SimpleDateFormat("yyyy-MM-dd"); // Tarih formatını şekillendirmek için oluşturulmuştur.
        String odaTarih = String.valueOf(tarihFormati.format(jXDatePicker1.getDate())); // Secilen tarih stringe atılıyor.
        String odaTipi = String.valueOf(jComboBox2.getSelectedItem());

        jTableOda
                .setDefaultEditor(Object.class,
                        null); // Tablonun kullanıcı tarafından uygulama calısırken degiştirilmesini engelliyor.

        //Mysql den veriler oda tipi ve tarihine göre özelliştirilmiş veriler çekiliyor.
        ResultSet rsRez = Veritabani.dbGoster("select * from otel where oda_tipi = '" + odaTipi + "' and oda_tarih ='" + odaTarih + "' and oda_doluMu ='" + 0 + "';");

        modelimOdaListe.setRowCount(0); // Her yeni arama yapıldıgında tablonun sıfırlanması için modelimin sutun sayısı 0 yapılmıştır.
        jTableOda.setModel(modelimOdaListe); // Tabloyu temizliyor.

        Object[] kolonlar = {"Oda No", "Oda Tipi", "Tarih"}; // Tablonun kolonları
        Object[] satirlar = new Object[3];   // Tablonun sutunları

        modelimOdaListe.setColumnIdentifiers(kolonlar);
        try {
            while (rsRez.next()) {
                String veritabani_odaTipi = rsRez.getString("oda_tipi");
                String veritabani_tarih = rsRez.getString("oda_tarih");
                String veritabani_odaNo = rsRez.getString("oda_id");
                satirlar[0] = rsRez.getString("oda_id");
                satirlar[1] = rsRez.getString("oda_tipi");
                satirlar[2] = rsRez.getString("oda_tarih");
                modelimOdaListe.addRow(satirlar);

                jTableOda.setModel(modelimOdaListe); //Tablonun modelini modelim yaparak veritabanından çekilen veriler tabloya yansıtılıyor.

            }
        } catch (SQLException ex) {

        }
        try {
            rsRez.close();

        } catch (SQLException ex) {
            Logger.getLogger(AdminSecim.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAraActionPerformed

    private void jbtnMusteriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMusteriEkleActionPerformed
        // **MÜŞTERİ EKLEME KISMI
        Musteri musteri = new Musteri();
        musteri.setmAd(jtxtisim.getText());
        musteri.setmSoyad(jTextFieldSoyisim1.getText());
        musteri.setmYas(Integer.parseInt(jTextFieldYas.getText()));
        musteri.setmMeslek(jTextFieldMeslek.getText());

        seciliOda = Integer.parseInt((String) modelimOdaListe.getValueAt(jTableOda.getSelectedRow(), 0));
        odaTipi = (String) modelimOdaListe.getValueAt(jTableOda.getSelectedRow(), 1);

        rezervasyonTipi = jcmbbxRezervasyonTip.getSelectedIndex();

        Rezervasyon.musteriRezervasyon(musteri);
    }//GEN-LAST:event_jbtnMusteriEkleActionPerformed

    private void jTextFieldSoyisim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoyisim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoyisim1ActionPerformed

    private void jTextFieldSoyisim1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSoyisim1MouseClicked
        jTextFieldSoyisim1.setText("");
        jTextFieldSoyisim1.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldSoyisim1MouseClicked

    private void jtxtisimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtisimActionPerformed

    }//GEN-LAST:event_jtxtisimActionPerformed

    private void jtxtisimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtisimMouseClicked
        jtxtisim.setText("");
        jtxtisim.setForeground(Color.black);
    }//GEN-LAST:event_jtxtisimMouseClicked

    private void jTextFieldKisiSayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKisiSayiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKisiSayiActionPerformed

    private void jTextFieldKisiSayiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldKisiSayiMouseClicked
        jTextFieldKisiSayi.setText("");
        jTextFieldKisiSayi.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldKisiSayiMouseClicked

    private void jlblMusteriEkleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMusteriEkleMouseClicked
        panelDegis(jpnlMusteriEkle);
        menuLabelDegis();
        jlblMusteriEkle.setForeground(Color.getColor("myColor"));
        jlblMusteriEkle.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\müsteriEkle_Mavi.png"));

    }//GEN-LAST:event_jlblMusteriEkleMouseClicked

    private void jlblMusteriCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMusteriCikisMouseClicked
        panelDegis(jpnlMusteriCikis);
        menuLabelDegis();
        jlblMusteriCikis.setForeground(Color.getColor("myColor"));
        jlblMusteriCikis.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\müsteriCikis_Mavi.png"));
    }//GEN-LAST:event_jlblMusteriCikisMouseClicked

    private void jlblSiparisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSiparisMouseClicked
        panelDegis(jpnlSiparis);
        menuLabelDegis();
        jlblSiparis.setForeground(Color.getColor("myColor"));
        jlblSiparis.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\siparis_Mavi.png"));
    }//GEN-LAST:event_jlblSiparisMouseClicked

    private void jTxtOdaNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtOdaNoMouseClicked
        jTxtOdaNo.setText("");
        jTxtOdaNo.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTxtOdaNoMouseClicked

    private void jtxtSiparisOdaNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSiparisOdaNoMouseClicked
        jtxtSiparisOdaNo.setText("");
        jtxtSiparisOdaNo.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtxtSiparisOdaNoMouseClicked

    private void jlblSistemGünlügüMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblSistemGünlügüMouseClicked
        panelDegis(jpnlSistemGünlügü); // düzeltilecek
        menuLabelDegis();
        jlblSistemGünlügü.setForeground(Color.getColor("myColor"));
        jlblSistemGünlügü.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\sistemGünlügü_Mavi.png"));
    }//GEN-LAST:event_jlblSistemGünlügüMouseClicked

    private void jbtnucretHesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnucretHesapActionPerformed
        odaNo = Integer.parseInt(jTxtOdaNo.getText());
        String musteriUcret = Musteri.ucretHesapla();
        jlblUcretMiktar.setText(musteriUcret);


    }//GEN-LAST:event_jbtnucretHesapActionPerformed

    private void jlblOdalarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblOdalarMouseClicked
        panelDegis(jpnlOdalar); // düzeltilecek
        menuLabelDegis();
        jlblOdalar.setForeground(Color.getColor("myColor"));
        jlblOdalar.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\odalar_Mavi.png"));
    }//GEN-LAST:event_jlblOdalarMouseClicked

    private void jbtnSistemGunlugunuGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSistemGunlugunuGosterActionPerformed
        String sql_sorgu = "SELECT * FROM Log";
        ResultSet rsSistem = Veritabani.dbGoster(sql_sorgu); // Veritabanindan sql sorgusu cekiliyor.

        jtblSistemgunlugu.setDefaultEditor(Object.class, null); // Tablonun kullanıcı tarafından düzenlenmesini engelliyor.

        DefaultTableModel modelimSistemGunlugu = new DefaultTableModel();
        modelimSistemGunlugu.setRowCount(0);
        Object[] kolonlar = {"Tarih", "İşlem", "Kullanıcı Adı", "Oda No"};
        Object[] satirlar = new Object[4];
        modelimSistemGunlugu.setColumnIdentifiers(satirlar);

        try {
            while (rsSistem.next()) {
                satirlar[0] = rsSistem.getString("log_tarih");
                satirlar[1] = rsSistem.getString("log_islem");
                satirlar[2] = rsSistem.getString("log_kullanıcı");
                satirlar[3] = rsSistem.getString("log_odaNo");
                modelimSistemGunlugu.addRow(satirlar);

                jtblSistemgunlugu.setModel(modelimSistemGunlugu);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminSecim.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSistemGunlugunuGosterActionPerformed

    private void jbtnKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKullaniciEkleActionPerformed
        Kullanici yeniKullanici = new Kullanici();    // Yeni bir kullanici nesnesi olusturup alınan degerler olusturulan nesneye veriliyor.
        if (jtxtKullaniciAd.isValid() || jtxtKullaniciSoyad.isValid() || jtxtKullaniciHesap.isValid() || jtxtKullaniciSifre.isValid()) {
            if (AdminGirisi.kullaniciAd.equals("admin")) {
                yeniKullanici.setKullaniciAd(jtxtKullaniciAd.getText());
                yeniKullanici.setKullaniciSoyad(jtxtKullaniciSoyad.getText());
                yeniKullanici.setKullaniciSifre(jtxtKullaniciSifre.getText());
                yeniKullanici.setKullaniciHesap(jtxtKullaniciHesap.getText());
                yeniKullanici.setKullaniciYetki((String) jcmbboxKullaniciYetki.getSelectedItem());

                yeniKullanici.kullaniciEkle();
            } else {
                jlblKullaniciEkleHata.setText("Geçersiz Yetki");
            }

        } else {
            jlblKullaniciEkleHata.setText("Bilgiler Boş Bırakılamaz.");

        }


    }//GEN-LAST:event_jbtnKullaniciEkleActionPerformed

    private void jtxtKullaniciAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKullaniciAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKullaniciAdActionPerformed

    private void jbtnKullaniciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKullaniciSilActionPerformed
        Kullanici silKullanici = new Kullanici();

        if (jtxtKullaniciHesapSil.isValid()) {
            if (AdminGirisi.kullaniciAd.equals("admin")) {
                silKullanici.setKullaniciHesap(jtxtKullaniciHesapSil.getText());
                silKullanici.kullaniciSil();
            } else {
                jlblKullaniciSilHata.setText("Geçersiz Yetki");
            }

        } else {
            jlblKullaniciSilHata.setText("Bilgiler boş bırakılamaz.");
        }


    }//GEN-LAST:event_jbtnKullaniciSilActionPerformed

    private void jbtnKullaniciGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKullaniciGuncelleActionPerformed
        Kullanici guncelleKullanici = new Kullanici();

        if (jtxtKullaniciHesapGuncelle.isValid()) {
            if (AdminGirisi.kullaniciAd.equals("admin")) {
                guncelleKullanici.setKullaniciHesap(jtxtKullaniciHesapGuncelle.getText());
                guncelleKullanici.setKullaniciSifre(jtxtKullaniciSifreGuncelle.getText());
                guncelleKullanici.setKullaniciYetki((String) jcmbboxKullaniciYetkiGuncelle.getSelectedItem());
                guncelleKullanici.kullaniciGuncelle();
            } else {
                jlblKullaniciGuncelleHata.setText("Geçersiz Yetki");
            }

        } else {
            jlblKullaniciGuncelleHata.setText("Bilgiler Boş Bırakılamaz.");
        }

    }//GEN-LAST:event_jbtnKullaniciGuncelleActionPerformed

    private void jtxtKullaniciAdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciAdMouseClicked
       jtxtKullaniciAd.setText("");
       jtxtKullaniciAd.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciAdMouseClicked

    private void jtxtKullaniciSoyadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciSoyadMouseClicked
       jtxtKullaniciSoyad.setText("");
       jtxtKullaniciSoyad.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciSoyadMouseClicked

    private void jtxtKullaniciHesapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciHesapMouseClicked
       jtxtKullaniciHesap.setText("");
       jtxtKullaniciHesap.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciHesapMouseClicked

    private void jtxtKullaniciSifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciSifreMouseClicked
       jtxtKullaniciSifre.setText("");
       jtxtKullaniciSifre.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciSifreMouseClicked

    private void jtxtKullaniciHesapSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciHesapSilMouseClicked
       jtxtKullaniciHesapSil.setText("");
       jtxtKullaniciHesapSil.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciHesapSilMouseClicked

    private void jtxtKullaniciHesapGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciHesapGuncelleMouseClicked
        jtxtKullaniciHesapGuncelle.setText("");
       jtxtKullaniciHesapGuncelle.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciHesapGuncelleMouseClicked

    private void jtxtKullaniciSifreGuncelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKullaniciSifreGuncelleMouseClicked
       jtxtKullaniciSifreGuncelle.setText("");
       jtxtKullaniciSifreGuncelle.setForeground(Color.black);
    }//GEN-LAST:event_jtxtKullaniciSifreGuncelleMouseClicked

    private void jlblKullaniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblKullaniciMouseClicked
        if(AdminGirisi.kullaniciAd.equals("admin")){
            panelDegis(jpnlKullanici);
            menuLabelDegis();
            jlblKullanici.setForeground(Color.getColor("myColor"));
            jlblKullanici.setIcon(new ImageIcon("C:\\Users\\muhammed\\Documents\\NetBeansProjects\\JavaProje\\src\\images\\kullanici_Mavi.png"));
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Geçersiz Yetki");
        }

    }//GEN-LAST:event_jlblKullaniciMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSecim.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSecim.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSecim.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSecim.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSecim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMusteriCikis;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAra;
    private javax.swing.JComboBox<String> jCmbbxOdaTip;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredpnlAna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableOda;
    private javax.swing.JTextField jTextFieldKisiSayi;
    private javax.swing.JTextField jTextFieldMeslek;
    private javax.swing.JTextField jTextFieldSoyisim1;
    private javax.swing.JTextField jTextFieldYas;
    private javax.swing.JTextField jTxtOdaNo;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JButton jbtnKullaniciEkle;
    private javax.swing.JButton jbtnKullaniciGuncelle;
    private javax.swing.JButton jbtnKullaniciSil;
    private javax.swing.JButton jbtnMusteriEkle;
    private javax.swing.JButton jbtnSiparisOnay;
    private javax.swing.JButton jbtnSistemGunlugunuGoster;
    private javax.swing.JButton jbtnucretHesap;
    private javax.swing.JComboBox<String> jcmbboxKullaniciYetki;
    private javax.swing.JComboBox<String> jcmbboxKullaniciYetkiGuncelle;
    private javax.swing.JComboBox<String> jcmbbtnSiparisTipi;
    private javax.swing.JComboBox<String> jcmbbxOdaDurum;
    private javax.swing.JComboBox<String> jcmbbxRezervasyonTip;
    private javax.swing.JLabel jlblExitbtn;
    private javax.swing.JLabel jlblKullanici;
    private javax.swing.JLabel jlblKullaniciEkle;
    private javax.swing.JLabel jlblKullaniciEkle1;
    private javax.swing.JLabel jlblKullaniciEkleHata;
    private javax.swing.JLabel jlblKullaniciGuncelle;
    private javax.swing.JLabel jlblKullaniciGuncelleHata;
    private javax.swing.JLabel jlblKullaniciSilHata;
    private javax.swing.JLabel jlblKullaniciYetki;
    private javax.swing.JLabel jlblKullaniciYetkiGuncelle;
    private javax.swing.JLabel jlblMinimizebtn;
    private javax.swing.JLabel jlblMusteriCikis;
    private javax.swing.JLabel jlblMusteriEkle;
    private javax.swing.JLabel jlblOdalar;
    private javax.swing.JLabel jlblSiparis;
    private javax.swing.JLabel jlblSistemGünlügü;
    private javax.swing.JLabel jlblUcret;
    private javax.swing.JLabel jlblUcretMiktar;
    private javax.swing.JPanel jpnlKullanici;
    private javax.swing.JPanel jpnlMusteriCikis;
    private javax.swing.JPanel jpnlMusteriEkle;
    private javax.swing.JPanel jpnlOdalar;
    private javax.swing.JPanel jpnlSiparis;
    private javax.swing.JPanel jpnlSistemGünlügü;
    private javax.swing.JTable jtableOdaListe;
    private javax.swing.JTable jtblSistemgunlugu;
    private javax.swing.JTextField jtxtKullaniciAd;
    private javax.swing.JTextField jtxtKullaniciHesap;
    private javax.swing.JTextField jtxtKullaniciHesapGuncelle;
    private javax.swing.JTextField jtxtKullaniciHesapSil;
    private javax.swing.JTextField jtxtKullaniciSifre;
    private javax.swing.JTextField jtxtKullaniciSifreGuncelle;
    private javax.swing.JTextField jtxtKullaniciSoyad;
    private javax.swing.JTextField jtxtSiparisOdaNo;
    private javax.swing.JTextField jtxtisim;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
