/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaproje;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.EtchedBorder;
import keeptoo.Drag;
import org.jdesktop.swingx.SwingXUtilities;

/**
 *
 * @author muhammed
 */
public class AdminGirisi extends javax.swing.JFrame {

    public static String kullaniciAd="";
    
    /**
     * Creates new form AdminGirisi
     */
    
    public AdminGirisi() {
        initComponents();
        System.setProperty("parlakKirmizi", "#E81123");
        System.setProperty("acikMavi", "#829afb");
        System.setProperty("kapaliMavi","#3366ff");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullanici1 = new javaproje.Kullanici();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPassKullanici = new javax.swing.JPasswordField();
        JTextKullanici = new javax.swing.JTextField();
        jLabelHata = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlblExitbtn = new javax.swing.JLabel();
        jlblMinimizebtn = new javax.swing.JLabel();
        jlblGirişbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Otel Rezervasyon");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(196, 220, 255));
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 255));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPassKullanici.setBackground(new Color(0,0,0,0));
        jPassKullanici.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPassKullanici.setForeground(new java.awt.Color(255, 255, 255));
        jPassKullanici.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPassKullanici.setText("Şifre");
        jPassKullanici.setBorder(null);
        jPassKullanici.setOpaque(false);
        jPassKullanici.setPreferredSize(new java.awt.Dimension(125, 22));
        jPassKullanici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPassKullaniciMouseClicked(evt);
            }
        });
        jPassKullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassKullaniciActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jPassKullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 182, 185, 37));

        JTextKullanici.setBackground(new Color(0,0,0,0));
        JTextKullanici.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JTextKullanici.setForeground(new java.awt.Color(255, 255, 255));
        JTextKullanici.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JTextKullanici.setText("Kullanıcı Adı");
        JTextKullanici.setBorder(null);
        JTextKullanici.setMaximumSize(new java.awt.Dimension(5, 5));
        JTextKullanici.setOpaque(false);
        JTextKullanici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTextKullaniciMouseClicked(evt);
            }
        });
        JTextKullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextKullaniciActionPerformed(evt);
            }
        });
        kGradientPanel1.add(JTextKullanici, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 123, 185, 34));

        jLabelHata.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHata.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabelHata.setForeground(new java.awt.Color(255, 51, 51));
        jLabelHata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHata.setToolTipText("");
        jLabelHata.setAlignmentY(0.0F);
        jLabelHata.setAutoscrolls(true);
        jLabelHata.setFocusable(false);
        kGradientPanel1.add(jLabelHata, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 222, 30));

        jSeparator1.setBackground(new java.awt.Color(242, 244, 244));
        jSeparator1.setForeground(new java.awt.Color(242, 244, 244));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 161, 185, 10));

        jSeparator2.setBackground(new java.awt.Color(242, 244, 244));
        jSeparator2.setForeground(new java.awt.Color(242, 244, 244));
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 225, 180, 10));

        jlblExitbtn.setBackground(new java.awt.Color(214, 45, 32));
        jlblExitbtn.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jlblExitbtn.setForeground(new java.awt.Color(255, 255, 255));
        jlblExitbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblExitbtn.setText(" X ");
        jlblExitbtn.setMinimumSize(new java.awt.Dimension(27, 32));
        jlblExitbtn.setPreferredSize(new java.awt.Dimension(27, 32));
        jlblExitbtn.setVerifyInputWhenFocusTarget(false);
        jlblExitbtn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jlblExitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblExitbtnMouseExited(evt);
            }
        });
        kGradientPanel1.add(jlblExitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, 32));

        jlblMinimizebtn.setBackground(new java.awt.Color(0, 204, 255));
        jlblMinimizebtn.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlblMinimizebtn.setForeground(new java.awt.Color(255, 255, 255));
        jlblMinimizebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMinimizebtn.setText(" - ");
        jlblMinimizebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblMinimizebtn.setPreferredSize(new java.awt.Dimension(27, 32));
        jlblMinimizebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblMinimizebtnMouseExited(evt);
            }
        });
        kGradientPanel1.add(jlblMinimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 10, 30, 32));

        jlblGirişbtn.setBackground(new java.awt.Color(51, 102, 255));
        jlblGirişbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblGirişbtn.setForeground(new java.awt.Color(255, 255, 255));
        jlblGirişbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblGirişbtn.setText("Giriş");
        jlblGirişbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlblGirişbtn.setOpaque(true);
        jlblGirişbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblGirişbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlblGirişbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlblGirişbtnMouseExited(evt);
            }
        });
        kGradientPanel1.add(jlblGirişbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 185, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otel_Beyaz.png"))); // NOI18N
        jLabel1.setText("Rezervasyon Sistemi");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 190, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextKullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextKullaniciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextKullaniciActionPerformed

    private void JTextKullaniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTextKullaniciMouseClicked
        JTextKullanici.setText("");
    }//GEN-LAST:event_JTextKullaniciMouseClicked

    private void jPassKullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassKullaniciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassKullaniciActionPerformed

    private void jPassKullaniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPassKullaniciMouseClicked
        jPassKullanici.setText("");
    }//GEN-LAST:event_jPassKullaniciMouseClicked

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed

    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        new Drag(kGradientPanel1).onPress(evt);
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void jlblExitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlblExitbtnMouseClicked

    private void jlblExitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseEntered

        Color myColor = Color.getColor("parlakKirmizi");
        jlblExitbtn.setBackground(myColor);
        jlblExitbtn.setOpaque(true);

    }//GEN-LAST:event_jlblExitbtnMouseEntered

    private void jlblExitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblExitbtnMouseExited
        jlblExitbtn.setBackground(Color.white);
        jlblExitbtn.setOpaque(false);

    }//GEN-LAST:event_jlblExitbtnMouseExited

    private void jlblMinimizebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jlblMinimizebtnMouseClicked

    private void jlblMinimizebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseEntered

        Color myColor2 = Color.getColor("acikMavi");
        jlblMinimizebtn.setBackground(myColor2);
        jlblMinimizebtn.setOpaque(true);
    }//GEN-LAST:event_jlblMinimizebtnMouseEntered

    private void jlblMinimizebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblMinimizebtnMouseExited

        jlblMinimizebtn.setBackground(Color.white);
        jlblMinimizebtn.setOpaque(false);
    }//GEN-LAST:event_jlblMinimizebtnMouseExited

    private void jlblGirişbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblGirişbtnMouseClicked
            kullaniciAd = JTextKullanici.getText();
           
        String kullaniciSifre = String.valueOf(jPassKullanici.getPassword());
        ResultSet rsAdmin = Veritabani.dbGoster("select * from admin");
        try {
            while (rsAdmin.next()) {
                String veritabani_kullanici = rsAdmin.getString("admin_kullanici");
                String veritabani_sifre = rsAdmin.getString("admin_sifre");

                if (kullaniciAd.equals(veritabani_kullanici) && kullaniciSifre.equals(veritabani_sifre)) {

                    System.out.println("Giris yapılmıstır"); // Kodu denetlemek amaçlı yazıldı. Sil
                    setVisible(false); // AdminGirisin görünülebilirligini false yapıyor
                    new AdminSecim().setVisible(true); // Admin Secim ekranı çagırıyor.

                } else {
                    jLabelHata.setText("Hatalı kullanıcı adı veya şifre girdiniz.");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGirisi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlblGirişbtnMouseClicked

    private void jlblGirişbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblGirişbtnMouseEntered
        jlblGirişbtn.setBackground(Color.getColor("acikMavi"));
    }//GEN-LAST:event_jlblGirişbtnMouseEntered

    private void jlblGirişbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblGirişbtnMouseExited
       jlblGirişbtn.setBackground(Color.getColor("kapaliMavi"));
    }//GEN-LAST:event_jlblGirişbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGirisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGirisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextKullanici;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHata;
    private javax.swing.JPasswordField jPassKullanici;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlblExitbtn;
    private javax.swing.JLabel jlblGirişbtn;
    private javax.swing.JLabel jlblMinimizebtn;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javaproje.Kullanici kullanici1;
    // End of variables declaration//GEN-END:variables
}
